navbar_title = "Shervin Sahba"
footer = "Copyright Â© 2021-2023 Shervin Sahba"
author = "Shervin Sahba"
color_scheme = "light" # "light" or "dark"
enable_toc = true
enable_collapsible_toc = true
enable_collapsible_changelogs = true

# Zooming.js
enable_zooming_js = true

# Site Search
enable_site_search = true

# Mathjax - inline and block math with $ and $$
enable_math = true

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Custom CSS
custom_css = ["css/academicons.css"]


[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = false


[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"
    [syntax_highlight.builtin]
    enable_code_copy = true
    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false
